###
GET http://localhost:5212/appointments 

###
GET http://localhost:5212/appointments/3

### Post new Appointment
POST http://localhost:5212/appointments
Content-Type: application/json

{
    "name": "Jack Sparrow",
    "doctorId": 2,
    "appointmentDateTime": "2025-04-10T10:00:00",
    "duration": "00:30:00",
    "appointmentType": "Follow-up",
    "notes": "Post-surgery checkup",
    "statusId": 3,
    "createdAt": "2025-03-31T14:30:00"
}

### Update Appointment
PUT http://localhost:5212/appointments/3
Content-Type: application/json

{
    "name": "Anna Michaels",
    "doctorId": 3,
    "appointmentDateTime": "2025-04-10T10:00:00",
    "duration": "00:30:00",
    "appointmentType": "Follow-up",
    "notes": "Doctors Appointment",
    "statusId": 5,
    "createdAt": "2025-03-31T14:30:00"
}

### Delete Appointment
DELETE http://localhost:5212/appointments/2





